<?php

/**
 * @file
 * Contains hook implementationsfor the Fullcalendar Scheduler module.
 */

/**
 * Builds the FullCalendar structure as a render array.
 */
function fullcalendar_scheduler_preprocess_fullcalendar(&$variables) {
  if ($variables['options']['fullcalendar_scheduler']['enabled']) {
    $variables += ['#attached' => []];
    $variables['#attached'] += ['library' => []];
    $variables['#attached']['library'][] = 'fullcalendar_scheduler/drupal.fullcalendar_scheduler';
  }
}
